### ISSUE TITLE
bug: `[No Name]` buffer created on every launch.

### ISSUE THREAD

**Issue by Aumnescio** [stefanwatt/trek.nvim#2]
# Problem

Every time the file explorer is launched, a `[No Name]` buffer is created. The created buffers are also not deleted after exiting the file explorer. However, I do not see why these buffers should be created in the first place.

It does not seem like the empty buffer is used for anything.

# Screenshots

![image](https://github.com/user-attachments/assets/7781f8ba-81e9-4752-91be-e9dd032838ef)

![image](https://github.com/user-attachments/assets/4a3a74bb-3dec-41f4-ac6d-e22584d217a5)

# Expected Behaviour

No unnecessary empty buffers are created.

# Extra Info

I installed using the recommended snippet in the README. I do have a decent amount of other plugins installed which could be messing with something, but I doubt this issue is happening because of another plugin. However, I did first notice it because I have a bufferline plugin active.

Edit: Pretty sure it's the `tabnew` call (`./lua/trek/window.lua:69`) creating the buffer, but nothing is using or cleaning that buffer up. Removing the `tabnew` call completely seems to be fine. The explorer still works fine and no useless buffer is created. Though if one of the splits is changed into an existing buffer, getting back to the explorer buffer does not seem possible. If then all the explorer splits are manually closed, the plugin will error when trying to launch the file explorer again. (These issues exist with or without the `tabnew` call.)

**Comment by stefanwatt** [comment]
Thanks for creating the issue and helping to make this plugin better ❤️
I will look into it. Should not be too hard to figure out.

> Removing the tabnew call completely seems to be fine

I think it makes sense to keep the UI of the plugin in a separate tab.
I guess when running tabnew it auto creates an empty buffer that I didn't account for.
Using that buffer instead of a newly created one seems to solve the problem

**Comment by stefanwatt** [comment]
@Aumnescio 
You can test the fix on the branch `bugfix/noname-buffers`
Seems to work fine as far as I can tell

**Comment by Aumnescio** [comment]
Hey, thanks. Seems like an improvement, and basically solves the core issue.

However, launching the file explorer is still creating a single scratch buffer that is "listed". Although quite a minor issue, this was still bothering me a bit and I was thinking there has to be some way to hide the buffer, so I tried figuring it out a bit.

```lua
// window.lua:72
vim.bo[window.left.buf_id].buflisted = false
```

It seems like just adding this line after the assert would work to hide the buffer. I would assume that this should not cause any problems, as the buffers are deleted by ID in the `close()` function. Also, the `nvim_create_buf()` function's first parameter is what is already disabling `buflisted` for the other buffers.

**Comment by stefanwatt** [comment]
good catch
